devtools::install_github('f-dallolio/fdutils', quiet = TRUE)
devtools::install_github('f-dallolio/adloadr', quiet = TRUE)

library(DBI, quietly = TRUE)
library(RPostgres, quietly = TRUE)
library(dm, quietly = TRUE)
library(tidyverse, quietly = TRUE)
library(dbplyr, quietly = TRUE)
library(readxl, quietly = TRUE)
library(glue, quietly = TRUE)
library(dbcooper, quietly = TRUE)
library(fdutils, quietly = TRUE)
library(adloadr, quietly = TRUE)
library(tictoc, quietly = TRUE)
